apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
  namespace: argocd
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"] 
  resources: ["ingresses"] 
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: argocd 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: argocd
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        - --source=ingress # ingress is also possible
        - --domain-filter=contrasting.org # (optional) limit to only example.com domains; change to match the zone created above.
        - --provider=cloudflare
        - --cloudflare-proxied # (optional) enable the proxy feature of Cloudflare (DDOS protection, CDN...)
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                  name: clf
                  key: token 
          - name: CF_EMAIL
            valueFrom:
              secretKeyRef:
                  name: clf
                  key: email 
