apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: resume 
spec:
  selector:
    matchLabels:
      app: resume 
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - name: resume
        image: gcr.io/badamscka/resume:1 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: resume
spec:
  selector:
    app: resume
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer 
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: certs@contrasting.org
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class:  nginx
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: contrasting-org 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-staging"
    # external-dns.alpha.kubernetes.io/hostname: contrasting.org
spec:
  rules:
  - host: contrasting.org
    http:
      paths:
      - path: /
        backend:
          serviceName: resume
          servicePort: 80
  tls:
  - hosts:
    - contrasting.org
    secretName: contrasting-org 
