kind: Service
apiVersion: v1
metadata:
  name: contrasting-org-prometheus
  labels:
    k8s-app: prometheus
    app.kubernetes.io/name: contrasting-org
    app.kubernetes.io/component: prometheus
spec:
  ports:
    # Exposes `http` and `TCP` ports `9090` using the default `ClusterIP` Service type
apiVersion: v1
kind: Service
metadata:
  name: prometheus-main
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: main
  sessionAffinity: ClientIP
  selector:
    k8s-app: prometheus
