apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  # name: USER@PROJECT.iam.gserviceaccount.com 
  name: terraform@badamscka.iam.gserviceaccount.com 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    external-dns.alpha.kubernetes.io/hostname: argocd.contrasting.org
    external-dns.alpha.kubernetes.io/ttl: "120" #optional

spec:
  rules:
  - host: argocd.contrasting.org
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: https

