apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: resume
  namespace: stage
spec:
  selector:
    matchLabels:
      app: resume 
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - name: resume
        image: gcr.io/badamscka/resume:61
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: resume
  namespace: stage
spec:
  selector:
    app: resume
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer 
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: contrasting-org 
  namespace: stage
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/ttl: "60" #optional
    external-dns.alpha.kubernetes.io/hostname: contrasting.org
spec:
  rules:
  - host: contrasting.org
    http:
      paths:
      - path: /
        backend:
          serviceName: resume
          servicePort: 80
  tls:
  - hosts:
    - stage.contrasting.org
    secretName: contrasting-org 
